require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BookOfClassesController do

  # This should return the minimal set of attributes required to create a valid
  # BookOfClass. As you add validations to BookOfClass, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all book_of_classes as @book_of_classes" do
      book_of_class = BookOfClass.create! valid_attributes
      get :index
      assigns(:book_of_classes).should eq([book_of_class])
    end
  end

  describe "GET show" do
    it "assigns the requested book_of_class as @book_of_class" do
      book_of_class = BookOfClass.create! valid_attributes
      get :show, :id => book_of_class.id.to_s
      assigns(:book_of_class).should eq(book_of_class)
    end
  end

  describe "GET new" do
    it "assigns a new book_of_class as @book_of_class" do
      get :new
      assigns(:book_of_class).should be_a_new(BookOfClass)
    end
  end

  describe "GET edit" do
    it "assigns the requested book_of_class as @book_of_class" do
      book_of_class = BookOfClass.create! valid_attributes
      get :edit, :id => book_of_class.id.to_s
      assigns(:book_of_class).should eq(book_of_class)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BookOfClass" do
        expect {
          post :create, :book_of_class => valid_attributes
        }.to change(BookOfClass, :count).by(1)
      end

      it "assigns a newly created book_of_class as @book_of_class" do
        post :create, :book_of_class => valid_attributes
        assigns(:book_of_class).should be_a(BookOfClass)
        assigns(:book_of_class).should be_persisted
      end

      it "redirects to the created book_of_class" do
        post :create, :book_of_class => valid_attributes
        response.should redirect_to(BookOfClass.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved book_of_class as @book_of_class" do
        # Trigger the behavior that occurs when invalid params are submitted
        BookOfClass.any_instance.stub(:save).and_return(false)
        post :create, :book_of_class => {}
        assigns(:book_of_class).should be_a_new(BookOfClass)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BookOfClass.any_instance.stub(:save).and_return(false)
        post :create, :book_of_class => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested book_of_class" do
        book_of_class = BookOfClass.create! valid_attributes
        # Assuming there are no other book_of_classes in the database, this
        # specifies that the BookOfClass created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BookOfClass.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => book_of_class.id, :book_of_class => {'these' => 'params'}
      end

      it "assigns the requested book_of_class as @book_of_class" do
        book_of_class = BookOfClass.create! valid_attributes
        put :update, :id => book_of_class.id, :book_of_class => valid_attributes
        assigns(:book_of_class).should eq(book_of_class)
      end

      it "redirects to the book_of_class" do
        book_of_class = BookOfClass.create! valid_attributes
        put :update, :id => book_of_class.id, :book_of_class => valid_attributes
        response.should redirect_to(book_of_class)
      end
    end

    describe "with invalid params" do
      it "assigns the book_of_class as @book_of_class" do
        book_of_class = BookOfClass.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BookOfClass.any_instance.stub(:save).and_return(false)
        put :update, :id => book_of_class.id.to_s, :book_of_class => {}
        assigns(:book_of_class).should eq(book_of_class)
      end

      it "re-renders the 'edit' template" do
        book_of_class = BookOfClass.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BookOfClass.any_instance.stub(:save).and_return(false)
        put :update, :id => book_of_class.id.to_s, :book_of_class => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested book_of_class" do
      book_of_class = BookOfClass.create! valid_attributes
      expect {
        delete :destroy, :id => book_of_class.id.to_s
      }.to change(BookOfClass, :count).by(-1)
    end

    it "redirects to the book_of_classes list" do
      book_of_class = BookOfClass.create! valid_attributes
      delete :destroy, :id => book_of_class.id.to_s
      response.should redirect_to(book_of_classes_url)
    end
  end

end
