require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CompetencesController do

  # This should return the minimal set of attributes required to create a valid
  # Competence. As you add validations to Competence, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all competences as @competences" do
      competence = Competence.create! valid_attributes
      get :index
      assigns(:competences).should eq([competence])
    end
  end

  describe "GET show" do
    it "assigns the requested competence as @competence" do
      competence = Competence.create! valid_attributes
      get :show, :id => competence.id.to_s
      assigns(:competence).should eq(competence)
    end
  end

  describe "GET new" do
    it "assigns a new competence as @competence" do
      get :new
      assigns(:competence).should be_a_new(Competence)
    end
  end

  describe "GET edit" do
    it "assigns the requested competence as @competence" do
      competence = Competence.create! valid_attributes
      get :edit, :id => competence.id.to_s
      assigns(:competence).should eq(competence)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Competence" do
        expect {
          post :create, :competence => valid_attributes
        }.to change(Competence, :count).by(1)
      end

      it "assigns a newly created competence as @competence" do
        post :create, :competence => valid_attributes
        assigns(:competence).should be_a(Competence)
        assigns(:competence).should be_persisted
      end

      it "redirects to the created competence" do
        post :create, :competence => valid_attributes
        response.should redirect_to(Competence.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved competence as @competence" do
        # Trigger the behavior that occurs when invalid params are submitted
        Competence.any_instance.stub(:save).and_return(false)
        post :create, :competence => {}
        assigns(:competence).should be_a_new(Competence)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Competence.any_instance.stub(:save).and_return(false)
        post :create, :competence => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested competence" do
        competence = Competence.create! valid_attributes
        # Assuming there are no other competences in the database, this
        # specifies that the Competence created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Competence.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => competence.id, :competence => {'these' => 'params'}
      end

      it "assigns the requested competence as @competence" do
        competence = Competence.create! valid_attributes
        put :update, :id => competence.id, :competence => valid_attributes
        assigns(:competence).should eq(competence)
      end

      it "redirects to the competence" do
        competence = Competence.create! valid_attributes
        put :update, :id => competence.id, :competence => valid_attributes
        response.should redirect_to(competence)
      end
    end

    describe "with invalid params" do
      it "assigns the competence as @competence" do
        competence = Competence.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Competence.any_instance.stub(:save).and_return(false)
        put :update, :id => competence.id.to_s, :competence => {}
        assigns(:competence).should eq(competence)
      end

      it "re-renders the 'edit' template" do
        competence = Competence.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Competence.any_instance.stub(:save).and_return(false)
        put :update, :id => competence.id.to_s, :competence => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested competence" do
      competence = Competence.create! valid_attributes
      expect {
        delete :destroy, :id => competence.id.to_s
      }.to change(Competence, :count).by(-1)
    end

    it "redirects to the competences list" do
      competence = Competence.create! valid_attributes
      delete :destroy, :id => competence.id.to_s
      response.should redirect_to(competences_url)
    end
  end

end
