require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InterimAttestationsController do

  # This should return the minimal set of attributes required to create a valid
  # InterimAttestation. As you add validations to InterimAttestation, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all interim_attestations as @interim_attestations" do
      interim_attestation = InterimAttestation.create! valid_attributes
      get :index
      assigns(:interim_attestations).should eq([interim_attestation])
    end
  end

  describe "GET show" do
    it "assigns the requested interim_attestation as @interim_attestation" do
      interim_attestation = InterimAttestation.create! valid_attributes
      get :show, :id => interim_attestation.id.to_s
      assigns(:interim_attestation).should eq(interim_attestation)
    end
  end

  describe "GET new" do
    it "assigns a new interim_attestation as @interim_attestation" do
      get :new
      assigns(:interim_attestation).should be_a_new(InterimAttestation)
    end
  end

  describe "GET edit" do
    it "assigns the requested interim_attestation as @interim_attestation" do
      interim_attestation = InterimAttestation.create! valid_attributes
      get :edit, :id => interim_attestation.id.to_s
      assigns(:interim_attestation).should eq(interim_attestation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new InterimAttestation" do
        expect {
          post :create, :interim_attestation => valid_attributes
        }.to change(InterimAttestation, :count).by(1)
      end

      it "assigns a newly created interim_attestation as @interim_attestation" do
        post :create, :interim_attestation => valid_attributes
        assigns(:interim_attestation).should be_a(InterimAttestation)
        assigns(:interim_attestation).should be_persisted
      end

      it "redirects to the created interim_attestation" do
        post :create, :interim_attestation => valid_attributes
        response.should redirect_to(InterimAttestation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved interim_attestation as @interim_attestation" do
        # Trigger the behavior that occurs when invalid params are submitted
        InterimAttestation.any_instance.stub(:save).and_return(false)
        post :create, :interim_attestation => {}
        assigns(:interim_attestation).should be_a_new(InterimAttestation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        InterimAttestation.any_instance.stub(:save).and_return(false)
        post :create, :interim_attestation => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested interim_attestation" do
        interim_attestation = InterimAttestation.create! valid_attributes
        # Assuming there are no other interim_attestations in the database, this
        # specifies that the InterimAttestation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        InterimAttestation.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => interim_attestation.id, :interim_attestation => {'these' => 'params'}
      end

      it "assigns the requested interim_attestation as @interim_attestation" do
        interim_attestation = InterimAttestation.create! valid_attributes
        put :update, :id => interim_attestation.id, :interim_attestation => valid_attributes
        assigns(:interim_attestation).should eq(interim_attestation)
      end

      it "redirects to the interim_attestation" do
        interim_attestation = InterimAttestation.create! valid_attributes
        put :update, :id => interim_attestation.id, :interim_attestation => valid_attributes
        response.should redirect_to(interim_attestation)
      end
    end

    describe "with invalid params" do
      it "assigns the interim_attestation as @interim_attestation" do
        interim_attestation = InterimAttestation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InterimAttestation.any_instance.stub(:save).and_return(false)
        put :update, :id => interim_attestation.id.to_s, :interim_attestation => {}
        assigns(:interim_attestation).should eq(interim_attestation)
      end

      it "re-renders the 'edit' template" do
        interim_attestation = InterimAttestation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InterimAttestation.any_instance.stub(:save).and_return(false)
        put :update, :id => interim_attestation.id.to_s, :interim_attestation => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested interim_attestation" do
      interim_attestation = InterimAttestation.create! valid_attributes
      expect {
        delete :destroy, :id => interim_attestation.id.to_s
      }.to change(InterimAttestation, :count).by(-1)
    end

    it "redirects to the interim_attestations list" do
      interim_attestation = InterimAttestation.create! valid_attributes
      delete :destroy, :id => interim_attestation.id.to_s
      response.should redirect_to(interim_attestations_url)
    end
  end

end
