require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SpecialitiesController do

  # This should return the minimal set of attributes required to create a valid
  # Speciality. As you add validations to Speciality, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all specialities as @specialities" do
      speciality = Speciality.create! valid_attributes
      get :index
      assigns(:specialities).should eq([speciality])
    end
  end

  describe "GET show" do
    it "assigns the requested speciality as @speciality" do
      speciality = Speciality.create! valid_attributes
      get :show, :id => speciality.id.to_s
      assigns(:speciality).should eq(speciality)
    end
  end

  describe "GET new" do
    it "assigns a new speciality as @speciality" do
      get :new
      assigns(:speciality).should be_a_new(Speciality)
    end
  end

  describe "GET edit" do
    it "assigns the requested speciality as @speciality" do
      speciality = Speciality.create! valid_attributes
      get :edit, :id => speciality.id.to_s
      assigns(:speciality).should eq(speciality)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Speciality" do
        expect {
          post :create, :speciality => valid_attributes
        }.to change(Speciality, :count).by(1)
      end

      it "assigns a newly created speciality as @speciality" do
        post :create, :speciality => valid_attributes
        assigns(:speciality).should be_a(Speciality)
        assigns(:speciality).should be_persisted
      end

      it "redirects to the created speciality" do
        post :create, :speciality => valid_attributes
        response.should redirect_to(Speciality.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved speciality as @speciality" do
        # Trigger the behavior that occurs when invalid params are submitted
        Speciality.any_instance.stub(:save).and_return(false)
        post :create, :speciality => {}
        assigns(:speciality).should be_a_new(Speciality)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Speciality.any_instance.stub(:save).and_return(false)
        post :create, :speciality => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested speciality" do
        speciality = Speciality.create! valid_attributes
        # Assuming there are no other specialities in the database, this
        # specifies that the Speciality created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Speciality.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => speciality.id, :speciality => {'these' => 'params'}
      end

      it "assigns the requested speciality as @speciality" do
        speciality = Speciality.create! valid_attributes
        put :update, :id => speciality.id, :speciality => valid_attributes
        assigns(:speciality).should eq(speciality)
      end

      it "redirects to the speciality" do
        speciality = Speciality.create! valid_attributes
        put :update, :id => speciality.id, :speciality => valid_attributes
        response.should redirect_to(speciality)
      end
    end

    describe "with invalid params" do
      it "assigns the speciality as @speciality" do
        speciality = Speciality.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Speciality.any_instance.stub(:save).and_return(false)
        put :update, :id => speciality.id.to_s, :speciality => {}
        assigns(:speciality).should eq(speciality)
      end

      it "re-renders the 'edit' template" do
        speciality = Speciality.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Speciality.any_instance.stub(:save).and_return(false)
        put :update, :id => speciality.id.to_s, :speciality => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested speciality" do
      speciality = Speciality.create! valid_attributes
      expect {
        delete :destroy, :id => speciality.id.to_s
      }.to change(Speciality, :count).by(-1)
    end

    it "redirects to the specialities list" do
      speciality = Speciality.create! valid_attributes
      delete :destroy, :id => speciality.id.to_s
      response.should redirect_to(specialities_url)
    end
  end

end
